### ISSUE TITLE
fail2ban

### ISSUE THREAD

**Issue by vonglahn** [riegercloud/install-nextcloud#19]
Hi,

I installed nextcloud with your script. It works good but I have problems with fail2ban. My DSL-IP adress is banned repeatedly. I guess it is the Android nextcloud client that causes the problems. My wife and I both have a Android phone with the client.
During the night my IP adress was banned and the only running client are the phones.

After disabling the nextcloud jail it is working now.

Do you have an idea how to handle that problem?

Regards Christian

**Comment by vonglahn** [comment]
Hi,

I'm so sorry. It was my iPad which was configured for the old nextcloud but I haven't used the calendar on my iPad for months. Everything is right with you configuration.

**Comment by riegercloud** [comment]
No worries - enjoy your Nextcloud!
