### ISSUE TITLE
Script doesn't check if latest.tar.bz2 was downloaded properly

### ISSUE THREAD

**Issue by klepptor** [riegercloud/install-nextcloud#21]
I just tried the script to install a new NC Server. Everything worked fine but download.nextcloud.com seems to have a certificate problem at the moment.

I did a wget https://download.nextcloud.com/server/releases/latest.tar.bz2 --no-check-certificate manually to bypass this mistake, but I think the script should check. if the download went ok and either stop if it fails or let the user decide if it should use the dangerous --no-check-certificate

**Comment by riegercloud** [comment]
Maybe this was related to Nextclouds update (13.0.5) today. I just gave it a trial and could download the file as expected. May I ask you to test again and send me a feedback and/or close this issue? Cheers, Carsten

**Comment by riegercloud** [comment]
Successfully tested - URL available again
