### ISSUE TITLE
Double entries to /etc/apt/sources.list if the script is called more than once

### ISSUE THREAD

**Issue by klepptor** [riegercloud/install-nextcloud#22]
Just used the script several times because of failed download of latest.tar.bz2, see issue #21 
Now there are double entries in /etc/apt/sources.list because there is no check, if the entries already exist!
No real Problem, but also not very nice! ;)

**Comment by riegercloud** [comment]
Fully aggree! Will be changed in the upcoming releases.

**Comment by riegercloud** [comment]
something like that:
if grep -x "deb http://nginx.org/packages/mainline/ubuntu/ bionic nginx" /etc/apt/ -r
{sed ...}

**Comment by riegercloud** [comment]
# Version 3.6
# Solved Issue 22 - rows 41-51:
# https://github.com/riegercloud/install-nextcloud/issues/22
