### ISSUE TITLE
Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user '

### ISSUE THREAD

**Issue by thedonquixotic** [riegercloud/install-nextcloud#27]
Successfully completed the script installation but when going to the page it got kind of wonky. 

Also how exactly are we supposed to to connect it to a domain name etc?

![screenshot from 2018-07-26 19-03-29](https://user-images.githubusercontent.com/9451726/43296801-2e04bf52-9113-11e8-8f8b-b6063d75f4b8.png)

**Comment by riegercloud** [comment]
What kind of infrastructure are you operating?
`uname -ar`
If you were running my script successfully the wizard won't appear - something went wrong while running the script. 

I guess, you ran it more than one time?  Did you try it on a blank system again?
Was the nextcloud database and user created properly?

**Comment by thedonquixotic** [comment]
`Linux thewiz 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

`ERROR 1524 (HY000): Plugin 'unix_socket' is not loaded` was the result when I entered your second commmand about mysql. I have just finished doing a wipe and I think everything should be clean. I got that error above earlier though also. I'm guessing that response is when there's no db created?

And please excuse my ignorance, but when you say "it is recommended to call" what do you mean? As in I should call that hostname by going to the end of the script and putting my intended host name there or something?

I'm not directly in posession of my domain name. I host my portfolio at https://www.jackalope.tech using Dreamhost and I have created a subdomain usin their DNS management tools that should be have a DNS record pointing to my home computers IP4 address. The subdomain I chose was cloud.jackalope.tech. So do I need to put that at the end of the script under the script so that it can be called and matched up with what the DNS is expecting?

**Comment by riegercloud** [comment]
could you please issue
`mysql --version`
Are you able to logon to your database server?
`mysql -hlocalhost -uroot -p`

I gues, your database server doesn't perform well or isn't started correctly.

At the end of the script a dialogue appears very similar to the following one:
![grafik](https://user-images.githubusercontent.com/20593693/43301878-09781f08-9168-11e8-8305-640ffb373aa4.png)
Your hostname was configured as your webserver servername and was shown as the URL to call in your browser?! Copy that  URL (examplarily "https://it-services"), open your browser and paste the URL.
You could change the URL to e.g. your server ip or rename your server...but you have to amend the /var/www/nextcloud/config/config.php with regards to the "trusted domains" serttings either.

**Comment by riegercloud** [comment]
Open your config.php
`sudo -u www-data vi /var/www/nextcloud/config/config.php`
paste a further trusted domain as shownas value '3':

'trusted_domains' =>
  array (
    0 => 'yourservername1',
    2 => 'yourservername2',
    3 => 'cloud.jackalope.tech',
  ),
From now your Nextcloud should grant access if you call the server using https://cloud.jackalope.tech
Assuming, your webserver is configured to listen to that sni either.
`vi /etc/nginx/conf.d/nextcloud.conf`
`... 
server_name yourservername1 yourservername2  cloud.jackalope.tech;
...`

**Comment by thedonquixotic** [comment]
Uh so this isn't really related to your script but I seem to have gotten myself in a bit of a pickle. I was trying to wipe mariadb off my drive and then reinstall it. But in the process I deleted the mysql files in the etc/init folder and now I can't get into mysql without doing it in safe mode. I can't write anything for user permissions etc in that mode and so I'm stuck. I've tried uninstalling and reinstalling mariadb but the problem persists. 

I guess I could always reinstall Ubuntu again but this will be the fourth time I've done that in like 2 weeks and I just finally got my UI tweaked the way I wanted so I'm feeling like the wind is taken out my sails a bit. 

Is there anyway I can just wipe the slate clean and start over with MariaDB etc? My attempts so far have not seemed to do it correctly.

**Comment by thedonquixotic** [comment]
Okay I'm trying to reinstall stuff using synaptic. And it appears to be stuck on the part where it should be reinstall mariadb 10.3   Or maybe it's just taking a long time. It's hard to tell. whew.... I really screwed this thing up.

**Comment by riegercloud** [comment]
OK...so may we close the issue for now?

**Comment by thedonquixotic** [comment]
Yeah sure thing. 

Also I think I figured it out. Looks like I had two different versions of MariaDB installed. I'll hit you back up once I get this thing fresh and restarted, if I have any further problems. Thank you! It's obvious you've put a lot of work into the script and the documentation for it in the script itself are really nice!
