### ISSUE TITLE
I'm afraid I'm back. Tried first script and can't connect to the url it gives me. 

### ISSUE THREAD

**Issue by thedonquixotic** [riegercloud/install-nextcloud#28]
I cleaned everything out as well as I could and tried to do a fresh install. And this is what I got:

```
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
Job for mariadb.service failed because the control process exited with error code.
See "systemctl status mariadb.service" and "journalctl -xe" for details.
```

And I ran the journalctl -xe thing it said to for more details and I got this:

```
Jul 27 03:09:01 thewiz CRON[8865]: pam_unix(cron:sessio
Jul 27 03:09:01 thewiz CRON[8864]: pam_unix(cron:sessio
Jul 27 03:09:03 thewiz kernel: [UFW AUDIT INVALID] IN=w
Jul 27 03:09:03 thewiz kernel: [UFW BLOCK] IN=wlx2016d8
Jul 27 03:09:14 thewiz kernel: [UFW AUDIT] IN=enp3s0 OU
Jul 27 03:09:18 thewiz kernel: [UFW AUDIT] IN= OUT=lo S
Jul 27 03:09:21 thewiz kernel: [UFW AUDIT] IN= OUT=enp3
Jul 27 03:09:21 thewiz kernel: [UFW ALLOW] IN= OUT=enp3
Jul 27 03:09:21 thewiz kernel: [UFW AUDIT] IN=enp3s0 OU
Jul 27 03:09:21 thewiz kernel: [UFW ALLOW] IN= OUT=wlx2
Jul 27 03:09:23 thewiz kernel: [UFW BLOCK] IN=enp3s0 OU
Jul 27 03:09:23 thewiz kernel: [UFW BLOCK] IN=wlx2016d8
Jul 27 03:09:31 thewiz kernel: [UFW BLOCK] IN=wlx2016d8
Jul 27 03:09:51 thewiz kernel: [UFW AUDIT] IN= OUT=enp3
Jul 27 03:09:51 thewiz kernel: [UFW ALLOW] IN= OUT=enp3
Jul 27 03:09:51 thewiz kernel: [UFW AUDIT] IN=enp3s0 OU
Jul 27 03:09:59 thewiz kernel: [UFW AUDIT] IN= OUT=enp3
Jul 27 03:09:59 thewiz kernel: [UFW ALLOW] IN= OUT=enp3
Jul 27 03:09:59 thewiz kernel: [UFW AUDIT] IN= OUT=enp3
Jul 27 03:09:59 thewiz kernel: [UFW ALLOW] IN= OUT=enp3
lines 1505-1524/1524 (END)
```

Any clues on what I should do differently?

**Comment by thedonquixotic** [comment]
I also decided to go ahead and try the second script because my thinking was, maybe the issue would go away if I just tried to connect using my subdomain name etc with https and.... well it didn't work either. 

Here was the error code I got:

```
at domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.

*** ERROR while requeting your certificate(s) ***

Verify that both ports (80 + 443) are forwarded to this server!
And verify, your dyndns points to your IP either!
Then retry...
```

I guess reading that last part, the dyndns, is that I would need to be able to see my server by going to cloud.jackalope.tech which I cannot? Which means that maybe my ports aren't forwarding? I'm using Google Fiber and my google fiber router has a smart port forwarding feature so I would expect it to do this stuff pretty easily. It seems to me that I need to get the first shell script working first in order to get the second. But I'm pretty clueless on what I should be examining with the first.

**Comment by thedonquixotic** [comment]
I ran the script again I kept noticing a particular set of nginx errors flipping by. I looked it up and someone on a stack exchange thread suggested running  `apt install -f ` without any packages and I did and I managed to get a readout again:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up nginx-core (1.14.0-0ubuntu1) ...
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
invoke-rc.d: initscript nginx, action "start" failed.
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2018-07-27 04:36:23 CDT; 5ms ago
     Docs: man:nginx(8)
  Process: 21997 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)

Jul 27 04:36:23 TheWiz systemd[1]: Starting A high performance web server and a reverse proxy server...
Jul 27 04:36:23 TheWiz nginx[21997]: nginx: [emerg] unknown directive "mp4" in /etc/nginx/conf.d/nextcloud.conf:40
Jul 27 04:36:23 TheWiz nginx[21997]: nginx: configuration file /etc/nginx/nginx.conf test failed
Jul 27 04:36:23 TheWiz systemd[1]: nginx.service: Control process exited, code=exited status=1
Jul 27 04:36:23 TheWiz systemd[1]: nginx.service: Failed with result 'exit-code'.
Jul 27 04:36:23 TheWiz systemd[1]: Failed to start A high performance web server and a reverse proxy server.
dpkg: error processing package nginx-core (--configure):
 installed nginx-core package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of nginx:
 nginx depends on nginx-core (<< 1.14.0-0ubuntu1.1~) | nginx-full (<< 1.14.0-0ubuntu1.1~) | nginx-light (<< 1.14.0-0ubuntu1.1~) | nginx-extras (<< 1.14.0-0ubuntu1.1~); however:
  Package nginx-core is not configured yet.
  Package nginx-full is not installed.
  Package nginx-light is not installed.
  Package nginx-extras is not installed.
 nginx depends on nginx-core (>= 1.14.0-0ubuntu1) | nginx-full (>= 1.14.0-0ubuntu1) | nginx-light (>= 1.14.0-0ubuntu1) | nginx-extras (>= 1.14.0-0ubuntu1); however:
  Package nginx-core is not configured yet.
  Package nginx-full is not installed.
  Package nginx-light is not installed.
  Package nginx-extras is not installed.

dpkg: error processing package nginx (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                                                   Errors were encountered while processing:
 nginx-core
 nginx
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I think it might be because I tried setting up an nginx server earlier tonight. I'm going to completely remove nginx and then run it again and maybe that will help.

**Comment by riegercloud** [comment]
The intial script didn't perform well on your system. NGINX isn't release 1.15.2 what causes the NGINX failure. Neither NGINX is able to start (quick solution: remove the mp4 section from your nextcloud.conf) nor ssl may be obtained as a consequence of the previous errors.
Something is wrong with your core server.

Please have a look whether /etc/apt/source.list.d/nginx.list exists or not.

**Comment by thedonquixotic** [comment]
@riegercloud I ran `/etc/apt/source.list.d/nginx`and the response from terminal was "no such file or directory". 

Ugh.... I really screwed this thing up. Is there anyway for me to fix this?I thought surely uninstalling and purging and then reinstalling should have worked. 

I just commented out the mp4 stuff and I'm running it again. I just passed the part where it asked me for a database username and password when I saw as it flicked by some kind of error like the last one where it asked me to check journalctl -xe or whatever. It's now asking me for an admin username and password to set for the db, and I'm going to continue the script but I imagine that something up above has already failed.

**Comment by riegercloud** [comment]
i didn't mean to issue the script again but restart nginx after having removed the mp4 section.
I suggest to wipe your server or reinstall. Then run the script and you will be fine.

As long as you have old fragments of software it won't work.
Did you try to
apt remove nginx nginx-common nginx-full -y --allow-change-held-packages --purge
apt remove mariadb-* --purge
and did you delete the directories as well?

**Comment by thedonquixotic** [comment]
Yup... seems to still not be working. Same output as before. 

```
22/tcp                     ALLOW IN    Anywhere                  
80/tcp (v6)                ALLOW IN    Anywhere (v6)             
443/tcp (v6)               ALLOW IN    Anywhere (v6)             
22/tcp (v6)                ALLOW IN    Anywhere (v6)             

Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.


++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

 Open your browser and call your Nextcloud at

 https://thewiz

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
root@TheWiz:/usr/local/src/install-nextcloud# systemctl status nginx.service
● nginx.service - A high performance web server and a reverse pr
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; v
   Active: failed (Result: exit-code) since Fri 2018-07-27 06:20
     Docs: man:nginx(8)
  Process: 1525 ExecStop=/sbin/start-stop-daemon --quiet --stop 
  Process: 30081 ExecStart=/usr/sbin/nginx -g daemon on; master_
  Process: 9573 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on;
 Main PID: 30082 (code=exited, status=0/SUCCESS)

Jul 27 06:20:23 TheWiz systemd[1]: Starting A high performance w
Jul 27 06:20:23 TheWiz nginx[9573]: nginx: [emerg] unknown direc
Jul 27 06:20:23 TheWiz nginx[9573]: nginx: configuration file /e
Jul 27 06:20:23 TheWiz systemd[1]: nginx.service: Control proces
lines 1-13
```

Also I checked to see /etc/apt/sources.list.d/nginx.list   I got the apt folder and there wasn't a directory called sources, but there was a text file and when I clicked on it in nautilus it opened up the software and updates application. Which from that I can guess that's the list that authorizes which sources and ppas etc my system can update from. I am... probably to blame here. In trying to completely purge my system and get rid of some weird apt update errors, I went through and removed a bunch of items in the list. I had multiple examples of the same items in there and it was getting quite full. I just now put two and two together. I remember seeing another post on here about that. So I guess I was overzeleaous in my pruning. 

I assumed that once I added stuff back in or reinstalled stuff etc it would fix that kind of thing, but I guess not. 

I'll run the purge commands you've listed and try again. I'm probably going to bed in a little bit. 

And I could just do another reinstall, it's just I kind of wanted to avoid that/ struggling with these things is kind of how I've been learning stuff. Anyway, I'll give the purge another shot. 

Also yes I did delete the directories as well. The ones I could find at least. 

Also I didn't do the -allow-change-held-packages which is why I'm going to try the purge and script again and see if that gets me any further. I'll let you know how it goes.  
```

**Comment by thedonquixotic** [comment]
Okay according to synaptic I've got nginx 1.14 installed (I installed it from the nginx ppa, that way I could add it back into my sources since it didn't seem to be comingback.) I'm now going to install mariadb. What version should I install? 10.1 or 10.3?

**Comment by thedonquixotic** [comment]
I'm installing 10.1 through synaptic. I took a look at my software center and I'm trying to exit, but it's taking a long time to finish the update cache process. So I'm going to catch some zzz and get cracking on this again in about 5ish hours. 

As always I don't to be bothering you. If the script doesn't work a final time after I get some sleep, I'm going to try an ansible build someone linked me and then I'm just going to wipe this sucker clean again. It's not fun to think about but it is what it is. Once I get this cloud thing up I hope to start regularly imaging my computers so this isn't such a pain each time.

**Comment by riegercloud** [comment]
Press my thumbs ;-)
