### ISSUE TITLE
Totally fresh install of Ubuntu 18.04 does not work with script. 

### ISSUE THREAD

**Issue by thedonquixotic** [riegercloud/install-nextcloud#29]
So I did a clean wipe of the system, I let the automatic updates at the beginning run and then I ran the script exactly as it is on the guide page here: https://www.c-rieger.de/spawn-your-nextcloud-server-using-one-shell-script/

When I opened up the screen to https://thewize as instructed, it showed me a screen for setting up admin account and database, which as I remember from my first attempt you said it should not do. I had  feeling it might do this because right after it ran the installation script I saw some big flashes of red highlighted text. The script kept on running so I couldn't really tell all what it said but what I caught glimpses of were something saying that NextCloud had not been installed and  something about Symphony and another thing about a limited available set of commands. And that's about all I could catch. 

Here's some pictures of the resulting login screen. I tried logging in with the exact same credentials that I put to be put into Maria DB, I tried logging in with out credentials and I tried logging in with totally invented new credientials. I also tried fiddling with the URL. I found that when I went to thewize:80 or thewize:443 and both redirected me to https://thewize as before, and did not work as before. 

![screenshot from 2018-07-27 21-48-29](https://user-images.githubusercontent.com/9451726/43352537-a0a1bd94-91ea-11e8-99c0-b11686915ac5.png)
![screenshot from 2018-07-27 21-50-44](https://user-images.githubusercontent.com/9451726/43352538-a0b1499e-91ea-11e8-83f5-8107f058472b.png)
![screenshot from 2018-07-27 21-53-40](https://user-images.githubusercontent.com/9451726/43352539-a0bf01ba-91ea-11e8-88aa-90d06957a220.png)
![screenshot from 2018-07-27 22-14-46](https://user-images.githubusercontent.com/9451726/43352541-a0cbb644-91ea-11e8-998f-39a0beb42cbe.png)
![screenshot from 2018-07-27 22-15-23](https://user-images.githubusercontent.com/9451726/43352542-a0dccc54-91ea-11e8-83ea-16d40c5413db.png)

Also here's some logs I found that I thought might be useful:

from /usr/lib/python3/dist-package/fail2ban/tests/files/logs/nginx-limit-req
```

# failJSON: { "time": "2015-10-29T20:01:02", "match": true , "host": "1.2.3.4" }
2015/10/29 20:01:02 [error] 256554#0: *99927 limiting requests, excess: 1.852 by zone "one", client: 1.2.3.4, server: example.com, request: "POST /index.htm HTTP/1.0", host: "exmaple.com"

# failJSON: { "time": "2015-10-29T19:24:05", "match": true , "host": "192.0.2.0" }
2015/10/29 19:24:05 [error] 12684#12684: *22174 limiting requests, excess: 1.495 by zone "one", client: 192.0.2.0, server: example.com, request: "GET /index.php HTTP/1.1", host: "example.com", referrer: "https://example.com"

# failJSON: { "time": "2016-09-30T08:36:06", "match": true, "host": "13.123.1.123" }
2016/09/30 08:36:06 [error] 22923#0: *4758725916 limiting requests, excess: 15.243 by zone "one", client: 13.123.1.123, server: example.com, request: "GET / HTTP/1.1", host: "example.com"

# failJSON: { "time": "2016-09-30T08:36:06", "match": true, "host": "2606:2800:220:1:248:1893:25c8:1946" }
2016/09/30 08:36:06 [error] 22923#0: *4758725916 limiting requests, excess: 15.243 by zone "one", client: 2606:2800:220:1:248:1893:25c8:1946, server: example.com, request: "GET / HTTP/1.1", host: "example.com"
```
same folder nginx-http-auth
```

# failJSON: { "time": "2012-04-09T11:53:29", "match": true , "host": "192.0.43.10" }
2012/04/09 11:53:29 [error] 2865#0: *66647 user "xyz" was not found in "/var/www/.htpasswd", client: 192.0.43.10, server: www.myhost.com, request: "GET / HTTP/1.1", host: "www.myhost.com"
# failJSON: { "time": "2012-04-09T11:53:36", "match": true , "host": "192.0.43.10" }
2012/04/09 11:53:36 [error] 2865#0: *66647 user "xyz": password mismatch, client: 192.0.43.10, server: www.myhost.com, request: "GET / HTTP/1.1", host: "www.myhost.com"
# failJSON: { "time": "2014-04-01T22:20:38", "match": true, "host": "10.0.2.2" }
2014/04/01 22:20:38 [error] 30708#0: *3 user "scribendio": password mismatch, client: 10.0.2.2, server: , request: "GET / HTTP/1.1", host: "localhost:8443"
# failJSON: { "time": "2014-04-02T12:37:58", "match": true, "host": "10.0.2.2" }
2014/04/02 12:37:58 [error] 6563#0: *1861 user "scribendio": password mismatch, client: 10.0.2.2, server: scribend.io, request: "GET /admin HTTP/1.1", host: "scribend.io", referrer: "https://scribend.io/admin"
# failJSON: { "time": "2014-04-03T22:20:38", "match": true, "host": "192.0.2.1", "desc": "user name with space" }
2014/04/03 22:20:38 [error] 30708#0: *3 user "scriben dio": password mismatch, client: 192.0.2.1, server: , request: "GET / HTTP/1.1", host: "localhost:8443"
# failJSON: { "time": "2014-04-03T22:20:40", "match": true, "host": "192.0.2.2", "desc": "trying injection on user name"}
2014/04/03 22:20:40 [error] 30708#0: *3 user "test": password mismatch, client: 127.0.0.1, server: test, request: "GET / HTTP/1.1", host: "localhost:8443"": was not found in "/etc/nginx/.htpasswd", client: 192.0.2.2, server: , request: "GET / HTTP/1.1", host: "localhost:8443"
```

same folder mongodb-auth
```
# failJSON: { "match": false }
2016-11-20T00:04:00.110+0100 [conn1] Failed to authenticate root@admin with mechanism MONGODB-CR: AuthenticationFailed UserNotFound Could not find user root@admin
# failJSON: { "time": "2016-11-20T00:04:00", "match": true , "host": "192.0.2.35" }
2016-11-20T00:04:00.111+0100 [conn1] end connection 192.0.2.35:53276 (0 connections now open)

# failJSON: { "match": false }
2016-11-20T00:24:00.110+0100 [conn5] Failed to authenticate root@admin with mechanism MONGODB-CR: AuthenticationFailed UserNotFound Could not find user root@admin
# failJSON: { "time": "2016-11-20T00:24:00", "match": true , "host": "192.0.2.171" }
2016-11-20T00:24:00.111+0100 [conn5] end connection 192.0.2.171:53276 (0 connections now open)

# failJSON: { "match": false }
2016-11-20T00:24:00.110+0100 [conn334] Failed to authenticate root@admin with mechanism MONGODB-CR: AuthenticationFailed key mismatch
# failJSON: { "time": "2016-11-20T00:24:00", "match": true , "host": "192.0.2.176" }
2016-11-20T00:24:00.111+0100 [conn334] end connection 192.0.2.176:53276 (0 connections now open)

# failJSON: { "match": false }
2016-11-20T00:24:00.110+0100 [conn56] Failed to authenticate root@admin with mechanism MONGODB-CR: AuthenticationFailed key mismatch
# failJSON: { "time": "2016-11-20T00:24:00", "match": true , "host": "192.0.2.1" }
2016-11-20T00:24:00.111+0100 [conn56] end connection 192.0.2.1:53276 (0 connections now open)

# failJSON: { "match": false }
2016-11-20T12:54:02.370+0100 [initandlisten] connection accepted from 127.0.0.1:58774 #2261 (1 connection now open)
# failJSON: { "match": false }
2016-11-20T12:54:02.370+0100 [conn2261] end connection 127.0.0.1:58774 (0 connections now open)

# failJSON: { "match": false }
2016-11-20T13:07:49.781+0100 [conn2271]  authenticate db: admin { authenticate: 1, nonce: "xxx", user: "root", key: "xxx" }
# failJSON: { "time": "2016-11-20T13:07:49", "match": false , "host": "192.0.2.178" }
2016-11-20T13:07:49.834+0100 [conn2271] end connection 192.0.2.178:60268 (3 connections now open)
```
Though looking at the dates modified it seems a lot of these log files might just be leftover or something from the Ubuntu development process. Anyway thought this might be of some help to you etc. Thanks!

**Comment by riegercloud** [comment]
Are all services in state "running"?  <= Redis, PHP, NGINX, MariaDB.
Please provide the status and all versions of each component (Redis, PHP, NGINX, MariaDB)

I guess, your server doesn't perform as expected and it isn't related to the script.

What do you mean by "clean wipe"? 
From my perspective you should reinstall your server OS with Ubuntu 18.04.1 LTS 64 Bit and then run the script. As you described a lot of old software fragments can be found on your system and those interrupt your server software!

**Comment by riegercloud** [comment]
Is your server on-prem, or a hosted one or...
You could provide me a ssh login and i will have a look?!

**Comment by thedonquixotic** [comment]
@riegercloud my host is on prem (I assume you mean on premises. It's a desktop computer in my closet)

By clean wipe I mean that I load an Ubuntu 18.04.1 usb boot stick and then format the drive and reinstall. 

I think this has to be something outside of linux related. I think maybe I haven't configured my router correctly. I'm going to try that. 

Also would totally be open to give you ssh login but I actually... don't know how to do that. What can I do to make that more possible?

**Comment by thedonquixotic** [comment]
Okay, this is kind of dumb but I think that I just didn't have my port forwarding rules set up correctly. I've gone over the ansible script created by Reiner Nippes which is based on your shell script, and I've double checked everything so I'm going to do another reinstall and try again.

**Comment by riegercloud** [comment]
Please keep in mind, as well Ubuntu as Debian provided new releases:
Ubuntu 18.04.1 LTS
Debian 9.5 stretch
Both OS are supported and you'll find guides in particular on my website.

**Comment by thedonquixotic** [comment]
Hey Rieger, it was a combination of multiple things (port forwarding issues, MariaDB not purging correctly, and a couple odds and ends). I got stuff working using Reiner Nippes ansible script adaption though. Thanks for putting the guide out there and talking through the process with me!
