### ISSUE TITLE
Nginx doesn't install with this script

### ISSUE THREAD

**Issue by Archerious** [riegercloud/install-nextcloud#35]
It seems Nginx isn't installing as using the restart.sh script gives an error that nginx isn't installed.

Please check the script.

**Comment by riegercloud** [comment]
Did you have a blank system?
What kind of OS?
Did you choose the AMD or ARM64 script?
What errors occured?

I cannot reproduce.

**Comment by Archerious** [comment]
> Did you have a blank system?
Yes, tried twice with two LXC VPS

> What kind of OS?
Ubuntu 18.04LTS

> Did you choose the AMD or ARM64 script?
AMD

> What errors occured?
# ./restart.sh
Failed to restart mysql.service: Unit mysql.service not found.
Failed to restart nginx.service: Unit nginx.service is masked.

**Comment by riegercloud** [comment]
I just set up lxd/lxc and could reproduce it.
The script fails on lxd/lxc.
I will investigate further if time permits.

**Comment by riegercloud** [comment]
I just created a new Bionic VirtualBox-environment. 
Then i started LXD/LCD from scratch:

```
lxc launch ubuntu:b itservices
lxc exec itservices -- /bin/bash
```
(as root)
```
apt install git -y
cd /usr/local/src
git clone https://github.com/riegercloud/install-nextcloud.git
cd install-nextcloud
chmod +x *.sh
./install-nextcloud.sh
```

it went through...except removing the bash_history.

![grafik](https://user-images.githubusercontent.com/20593693/47621893-4b9e1600-dafe-11e8-8a7d-72168d73b82c.png)


Could you please re-test this way?

**Comment by Archerious** [comment]
> Could you please re-test this way?

Sure. Just deleted this LXC container and created a new LXC VPS.

```
apt install git -y
cd /usr/local/src
git clone https://github.com/riegercloud/install-nextcloud.git
cd install-nextcloud
chmod +x *.sh
./install-nextcloud.sh
```

Did as instructed, still can't access anything.

When I run restart.sh:

```
root@nextcloud-ubuntu18:/usr/local/src/install-nextcloud# ./restart.sh
Failed to stop nginx.service: Unit nginx.service not loaded.
Failed to restart mysql.service: Unit mysql.service not found.
Failed to restart nginx.service: Unit nginx.service not found.
root@nextcloud-ubuntu18:/usr/local/src/install-nextcloud#

```

**Comment by Archerious** [comment]
If I run the command for status you ran in the screenshot: 

```
root@nextcloud-ubuntu18:/usr/local/src/install-nextcloud# sudo -u www-data php /var/www/nextcloud/occ status
Nextcloud is not installed - only a limited number of commands are available
  - installed: false
  - version: 14.0.3.0
  - versionstring: 14.0.3
  - edition:
root@nextcloud-ubuntu18:/usr/local/src/install-nextcloud#

```

**Comment by riegercloud** [comment]
Just made amendments to the script and was able to fix it (hopefully) by adding 
`apt install gnupg2 wget -y`
at the beginning of this script. I would really appreciyte your re-testing...

MERRY CHRISTMAS!
Carsten

**Comment by riegercloud** [comment]
I got feedback from different users - worked on Ubuntu 18.04 with LXD as expected
