### ISSUE TITLE
Change nextcloud data location

### ISSUE THREAD

**Issue by mrdeadlocked** [riegercloud/install-nextcloud#37]
Script works great! It would be nice if we could move where nextcloud stores its data during the script install process. I can't seem to not break nextcloud when doing it after install.

**Comment by riegercloud** [comment]
It is very simple to change it afterwards using "su -" or "sudo -s":
(1) stop the main services

`service nginx stop && service mysql stop`
`cp /var/www/nextcloud/config/config.php /var/www/nextcloud/config/config.php.bkup`
`vi /var/www/nextcloud/config/config.php`

(2) amend the nextcloud-datapath and save the config.php file

'datadirectory' => '/var/nc_data',
to
'datadirectory' => '/new/directory',

(3) apply the proper permissions

`chown www-data:www-data /var/www/nextcloud/config/config.php`

(4) move the data to your desired destination 

`rsync -av /var/nc_data/ /new/directory`

(5) apply the proper permissions to your destination folder

`chow -R www-data:www-data /new/directory`

(6) restart the earlier stopped services

`service mysql restart && service nginx restart `

(7) issue the optimization-debian.sh or optimization-ubuntu.sh from https://github.com/riegercloud/install-nextcloud and you will be fine.
